### ISSUE TITLE
Unable to create Route53 PTR record - error parsing template

### ISSUE THREAD

**Issue by mtimchenko-fz** [wallix/awless#133]
Hi !

I'm trying to create a PTR record in Route53 using lastly avaialble awless version=v0.1.2 :

awless -p MYPROFILE -r MYREGION create record name="10.10.10.10.in-addr.arpa." ttl=300 type=PTR value=host01.test.domain.cxm zone=MYZONE

and receiving : 

[error]   error parsing template at line 1 (char 45):
        -> create record name=10.10.10.10.in-addr.arpa.

What could be wrong ?

thanks

**Comment by simcap** [comment]
@mtimchenko-fz Thanks.

Indeed this would be due to our [PEG parsing that detects an IP](https://github.com/wallix/awless/blob/3c71be2e875e144d7e7e5dba1a4c88230d498117/template/internal/ast/awless-template-syntax.peg#L55) form (starting with 10.0.0.0) and then bails out as it cannot parse it correctly.

We will fix that (and probably remove type parsing from the PEG)

In the meantime to execute it from your console put the entire value of your record's name in double quote and backslash them (necessary for bash correct interpretation) like so `awless create record name=\"10.10.10.10.in-addr.arpa.\" ttl=300 ...`

I tested it and it will work.

**Comment by mtimchenko-fz** [comment]
Thank you. 

I confirm - it works with backslashed + double quotes.
