### ISSUE TITLE
Ability to follow CloudFormation stack update/create events.

### ISSUE THREAD

**Issue by Trane9991** [wallix/awless#143]
Would be nice to have to command something like:

`awless show stack-events --follow stack=<stack_name>`

Use case:
Using `awless` to deploy CloudFormation templates with CI and be able to keep track of the events.

**Comment by simcap** [comment]
Good idea indeed, and `awless` always try to be CI friendly!

As you have noticed rightly `stack-events` have an event/log nature (i.e. timelined, transient & contextualized text info) and the `list` or `show` command are not well suited for that. This would mean also that `stack-events` would be stored in your synced/local cloud model which would not be ideal.

So for this type of objects we are more thinking in terms of a dedicated `awless {stream,tail}` and actually we already implemented it to tail events from the CLI as a proof of concept but so far it is hidden in `awless`(type `awless tail -h` to reveal usage). 

So the case of `stack-events` this command would allow:

```
awless tail stack-events --ref MY_STACK_ID
```

So we might move in that direction (instead of augmenting the show command).

**Comment by Trane9991** [comment]
Example of some Go tool for deployment of CloudFormation stacks:
https://github.com/capitalone/stack-deployment-tool

@fxaguessy @simcap  do you practice assignment of people to the issue?

Maybe I will have some spare time to work on this, I just want to know if somebody working on it before begin.

**Comment by simcap** [comment]
@Trane9991 Thanks for stack deployment tool link!

We do not really assign yet. Basically we have to implement a `tailer` (see [tailers dir](https://github.com/wallix/awless/tree/master/aws/tailers) ). Tailers are still experimental but comes in handy and we do use them. 

Do not hesitate to take a stab at it with a PR. If we do the implementation on our side we will try to remember to assign ourselves to this issue.
