### ISSUE TITLE
--tag key=value not working

### ISSUE THREAD

**Issue by jdonnerstag** [wallix/awless#173]
Hi, 

awless version is v0.1.8, os=windows

It seems as if the --tag filter is not working
awless list instances --tag key=Owner

I validated that at least one instance has this tag (and proper case). But the command above returns an empty list. I tried various combinations but did not get it working

thanks for your help
Juergen

**Comment by simcap** [comment]
Hi @jdonnerstag

It seems to be a typo issue on your flag as `--tag key=val` is improper. It should be `--tag-key val`, looking at the command help (i.e. `awless list -h`, or just `awless ls`).

Basically, here all flags work on my side for me (note all case sensitive):

`awless ls instances --tag-key=Name`
 `awless ls instances --tag-value=debian`

or 

`awless ls instances --tag Name=debian`

Full definition with `awless ls -h`

**Comment by jdonnerstag** [comment]
thanks for the explanation. But then your "homepage" (https://github.com/wallix/awless) is not correct. There it says:
Listing filters via resources properties or resources tags: --filter property=val, --tag Key=Value

**Comment by jdonnerstag** [comment]
May I ask, and I don't find it using --help, is there a way to search for resources **not** having a specific tag key or value?

And **listing** all resources, not restricted to instances or databases or ..., , I guess is somewhat against awless general command line pattern. It is not supported, correct? Since all the data are available in your local RDF store, is there an easy way to query the store from a commandline?

Many thanks for your help

**Comment by simcap** [comment]
Homepage is correct but can be confusing since I took `Key=Value` as an example. I will update it to avoid confusion.

The listing is usually used for resources you know the type of. But to search for resources at the moment that would be using the `awless show -h` command.

In term of listing all resources, we are thinking of ways for doing that properly. 

Also soon enough we should have a more dedicated query language that can be used from the CLI.
