### ISSUE TITLE
What is the "awlessid" when listing route53 records?

### ISSUE THREAD

**Issue by deinspanjer** [wallix/awless#176]
Is there any way to use it as a reference or short cut so you don't have to specify every parameter (name type record ttl zone) when you are trying to delete a record?

**Comment by fxaguessy** [comment]
That's a very good suggestion that we will implement!
At first, `awlessId` was created in records because there was no ID of record in AWS API (and we need one ID in awless). But, for now, you can only use it with `awless show awls-1a1b102`. But a nice extension is to use it also in templates. We will try to implement that for next release, stay tuned.

**Comment by fxaguessy** [comment]
This has been implemented in 633d5527840c265cb39b1cb8a178dc4837fa0466.

You can now delete a record with 
- `awless delete record id=awls-1234beef` or 
- `awless delete record id=@my.sub.domain.com`

by building latest `awless` with `go get` or waiting next release)
