### ISSUE TITLE
Error: no access key set for instance

### ISSUE THREAD

**Issue by linuxbsdfreak** [wallix/awless#59]
Hi,

I am trying to login to the instances under a tmux session which is already having the keys loaded.

awless ssh username@instance-id
Error: no access key set for instance-id

Gives me the following error. Do you know wht do i need to configure to set the location to the private key?

Regards,
Kevin

**Comment by fxaguessy** [comment]
If you list your instances with `awless list instances`, you should see that the "ACCESS KEY" property for your instance is empty. That's why `awless ssh` do not automatically detect the key it should use (which must be stored in the `~/.awless/keys` folder).

For now, you cannot specify a specific key to use to connect via `awless ssh`, but there is an opened issue, #54, that aims at doing that.

**Comment by linuxbsdfreak** [comment]
Hi.

It still doesnt work. I have the key named test-thor.pem under ~/.awless/keys folder and still says

Error: no access key set for instance

Regards,
Kevin

**Comment by fxaguessy** [comment]
When you list instances with `awless list instances`. Do you have something in the `ACCESS KEY` column, for the instance you try to SSH in ?

**Comment by linuxbsdfreak** [comment]
Nothing.

**Comment by fxaguessy** [comment]
OK. So this is a normal behavior.  For now, `awless` do not test all keys in `~/.awless/keys` as a classic SSH client does. It only takes the key referenced in the `ACCESS KEY` property, if it exists.

**Comment by linuxbsdfreak** [comment]
Ok. So how do i fix this? Also i have few instances with ACCESS KEY property set and it gives me another error Error: ssh: cannot decode encrypted private keys. I have the private keys loaded with ssh-agent

**Comment by fxaguessy** [comment]
Are these access keys either RSA, DSA or ECDSA keys ?
