### ISSUE TITLE
It doesn't propagate special keystrokes

### ISSUE THREAD

**Issue by padilo** [wallix/awless#65]
When you send a `Ctrl+D`, it doesn't logout correctly on a ssh session, It justs hangs. It seems to be waiting for something

**Comment by kothar** [comment]
Same seems to be true for arrow keys, so I assume that control codes are not being sent correctly. (MacOS Sierra 10.12.3).

When you press `Ctrl+C` it just kills awless rather than passing the control code to the remote server.

awless is currently running its own pure-go ssh client, which presumably doesn't handle terminal emulation very well. Perhaps if an ssh or equivalent command is available on the system awless could invoke it using syscall.Exec on POSIX (This is an error on Windows by the look of it):

https://gobyexample.com/execing-processes

**Comment by edubxb** [comment]
Same problem here (OS Debian Testing)

**Comment by fxaguessy** [comment]
This is "normal". For now, we do not propagate special keystrokes such as `Ctrl+D` or `Ctrl+C`... But this is something that we want to add in the future.

**Comment by fxaguessy** [comment]
Fixed by f00c43e5bc9a14def33b4c992946642f61d449bc: If a ssh client is present on the machine, awless uses this client to connect to the instance (which will support special keystroke).
This is available in [0.0.17](https://github.com/wallix/awless/releases/tag/0.0.17).
