### ISSUE TITLE
Are awless templates idempotent?

### ISSUE THREAD

**Issue by rbellamy** [wallix/awless#72]
When re-runninng an awless template, am I guaranteed idempotency?

One of the major challenges working with ansible and AWS is that most ansible AWS modules are not idempotent. And no, Terraform is not the answer (https://charity.wtf/tag/terraform/). Chef is generally idempotent by design.

[Cross posted](http://stackoverflow.com/questions/42499416/are-awless-templates-idempotent) on StackOverflow (with Downvote!!!). I had assumed that questions go to SO and issues come here - but maybe `awless` isn't established enough to need that?

**Comment by hbbio** [comment]
As a general rule, it seems impossible to guarantee idempotency.

For instance, 

- deleting resources that contain data can't be recreated
- IP adresses of instances will change unless we use Elastic IP (which we can't use by default since they are not free when not attached and to be idempotent we would have to keep them).

Therefore, *some* templates may be idempotent but not all. As we plan more work on the awless templates formalization, we might have a look at determining idempotency, or even doing in the very long term doing program transformations to derive idempotent versions of some templates.
