### ISSUE TITLE
[RFE] take region from $AWS_DEFAULT_REGION

### ISSUE THREAD

**Issue by gfa** [wallix/awless#73]
Hello

I manage environments on different regions, and its a pain to reconfigure awless every time i switch region
would be super cool if awless could take the value from $AWS_DEFAULT_REGION  same as awscli

thanks for a great tool

**Comment by fxaguessy** [comment]
We just added two ways to handle this. Either with the `AWS_DEFAULT_REGION` env variable, or (preferably)  with the `--aws-region us-west-1` global flag. See [Changelog](https://github.com/wallix/awless/blob/master/CHANGELOG.md) for more details.
This is actually on master and will be soon in `0.0.17`.

**Comment by gfa** [comment]
Hello

apologies, I think i wasn't clear when i opened the issue

awless shouldn't create configuration files from env variables, it should use them during their lifetime and forget about it.

I don't want to have any setting in ~/.awless because i change environments (and customers) all the time, nothing should be hardcoded in my configuration files but derived from environmental variables.

building from master i wasn't able to use --aws-region switch 

thanks!

**Comment by fxaguessy** [comment]
Perhaps the CHANGELOG was not clear enough, but I think that what you want is almost what has been implemented. There is now 3 ways to customize the region in `awless`:
1. The `aws.region` key in the awless config
2. The `AWS_DEFAULT_REGION` env variable
3. The `--aws-region` global flag

At runtime, the latest overwrite the previous ones. For example, if you set the `AWS_DEFAULT_REGION` env variable, this will be taken into account, and not the awless config key. Similarly, the `--aws-region` overwrite `AWS_DEFAULT_REGION` and awless config key.

This is almost the same for AWS profile, except that, for now, the `AWS_DEFAULT_PROFILE` do not yet override `aws.profile` config. But we will add this very soon.

Are you sure that you used the latest version on master (8345814d0db328bc436aa4da208013fb79495f8a) because in this version, `awless list subnets -v --aws-region us-east-1` and `awless list subnets -v --aws-region us-east-2` will not list the same elements.

Note that if you want to better debug the region and profile used when using AWS, add the `-v` flag.

**Comment by gfa** [comment]
you are right, i can get want i want using master,  and the overrides work as expected.

sorry again for the noise
