### ISSUE TITLE
ssh using private ip

### ISSUE THREAD

**Issue by padilo** [wallix/awless#86]
Right now If I'm not wrong it uses public instance ip to connect to instances.

I would like a way to do it using private IPs. If you think if have sense I can try to do it ;)

**Comment by fxaguessy** [comment]
You want to use `awless ssh` from an AWS instance, in the same private network as the one you want to SSH in ?

This could be implemented by adding a `--private` flag in `awless ssh`and take into account this flag in the [`instanceCredentialsFromGraph` function](https://github.com/wallix/awless/blob/master/commands/ssh.go#L101).

**Comment by padilo** [comment]
Right now we use DirectConnect.
I'm not an expert about it, but I think using private IP will be useful for people using a bastion host too.
I'll try to do it then ;)

**Comment by cristim** [comment]
The problem is identifying the bastion host that has to be used, in case there are more of them.

Such a bastion host would need to have a public IP and also has to be in a subnet properly connected/routed/allowed to reach the target instance. This can get complex since it would need querying of subnets, VPCs and security groups, but would be definitely cool once implemented.
