### ISSUE TITLE
Possibility to list & delete AMI & Snapshot

### ISSUE THREAD

**Issue by chrisLeeTW** [wallix/awless#91]
It would be cool to have the possibility to list or delete my AMIs & Snapshot with filter by name or tags.

It's really useful for AMI cleanup / rotate task.

**Comment by fxaguessy** [comment]
Thanks for the suggestion.

For now, you can list images (AMIs) and filter by name with `awless list images --filter name=your-keyword`. In order to delete them, you can write a little bash oneliner, for example 

    awless list images --filter name=your-keyword --format tsv | tail -n +2 | cut -f 1 | xargs -n1 awless delete image id=

Be sure that the output is correct before adding `-f` flag to the `awless delete` command, in order to effectively delete the images.

For now we do not support filtering by tags (other than name), but this is something we want to add in the future.

**Comment by fxaguessy** [comment]
Since [v0.0.24](https://github.com/wallix/awless/releases/tag/v0.0.24), you can now [filter by tags](https://github.com/wallix/awless#listing-and-filtering-via-tags).

    awless list images --tag-value Prod
    awless list images --tag Env=Prod

With a oneliner like above, you can easily list and delete images filtered by tags and/or names:

    awless list images --tag Env=Test --format tsv | tail -n +2 | cut -f 1 | xargs -n1 awless delete image id=
