### ISSUE TITLE
Use certificates in ~/.ssh

### ISSUE THREAD

**Issue by sdouche** [wallix/awless#98]
Hi.
`awless ssh` is fucking useful command but it would be cool to use the _natural_ directory aka `~/.ssh/`. IMHO `~/.awsless` must only be used to store awless-centric informations.

**Comment by fxaguessy** [comment]
Hi, thanks for the feedback.

What is you use case ? Do you want to read existing keys already stored in ~/.ssh or write your new keys (generated with `awless create keypair`) in ~/.ssh ?

We didn't want to write in `~/.ssh` folder without user authorization. So perhaps we could at least read keys from both `~/.awless/keys` and `~/.ssh`. Otherwise, if you also would like to generate keys directly in `~/.ssh` we could provide a config parameter to change the keys folder.

**Comment by sdouche** [comment]
Hi

> What is you use case ? Do you want to read existing keys already stored in ~/.ssh

Yep.

> So perhaps we could at least read keys from both ~/.awless/keys and ~/.ssh. Otherwise, if you also would like to generate keys directly in ~/.ssh we could provide a config parameter to change the keys folder.

Both is fine to me.
